### ISSUE TITLE
Run page and code through Lighthouse Tool; Create report to discuss

### ISSUE THREAD

**Issue by jasonclark** [PeytonEllis/Walking-Tour-Spring-2022#2]
Background article: 
https://developers.google.com/web/tools/lighthouse#psi

Online tool: 
https://pagespeed.web.dev/?utm_source=psi&utm_medium=redirect

TODO:
- Create Lighthouse report to share.
- Make notes of where code can be improved and be ready to discuss.

**Comment by PeytonEllis** [comment]
https://montanaedu-my.sharepoint.com/:w:/r/personal/k93j787_msu_montana_edu/_layouts/15/Doc.aspx?sourcedoc=%7BD0AF31DA-8974-43C5-AC16-22F7A0BE0FF0%7D&file=Lighthouse.docx&action=default&mobileredirect=true
