### ISSUE TITLE
Create container for app and deploy to Azure

### ISSUE THREAD

**Issue by jasonclark** [PeytonEllis/Walking-Tour-Spring-2022#6]
The goal here is to automate and package our app using a container utility. For reference, use the following article - https://betterprogramming.pub/host-your-static-website-in-azure-as-a-docker-container-be127f00267d

**Comment by PeytonEllis** [comment]
![image](https://user-images.githubusercontent.com/43453578/163226072-4683f13f-89a9-45d5-8c70-0f284f2f7cb8.png)

**Comment by jasonclark** [comment]
Peyton got a VM running with the app. See screenshot.
<img width="1075" alt="Screen Shot 2022-04-13 at 10 19 12 AM" src="https://user-images.githubusercontent.com/494421/163226206-adbd36e9-f3fd-40b4-8b01-8b4003395ce5.png">
